@startuml


database ArticlesStorage{
	entity Article{
		id : UUID
		title : String
		date : Date
		author : String
		description : String
		categories : String
		tags : List<String>
		fileGzip : byte[]
	}
}

@enduml