version: '3.5'

services:
  db:
    image: mysql:latest
    container_name: mysql-baremetalio
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: baremetalio
    ports:
      - "33006:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
